### ISSUE TITLE
Standart scrollbars inside page are not replaced

### ISSUE THREAD

**Issue by mbratukha** [Christoph142/modern-scroll#50] opened 2015-02-02 04:52 UTC
Example (ver. 3.0.6): http://stackoverflow.com/questions/1255512/how-to-draw-a-rounded-rectangle-on-html-canvas

In ver.3.0.5 the behavior of scrollbars on the same page was strange.

![screenshot 2015-02-02 05 49 59](https://cloud.githubusercontent.com/assets/1413357/5995978/73de1bb2-aa9f-11e4-9678-9922a67a2858.png)

**Comment by Christoph142** [comment] 2015-02-02 07:55
You really are a good tester :)

**Comment by bratukham** [comment] 2015-02-02 07:57
I'm just trying to make a good extension much better :)

**Comment by Christoph142** [comment] 2015-02-02 07:58
Und warum macht ein Stuttgarter das um 5 Uhr nachts? :P

**Comment by bratukham** [comment] 2015-02-02 08:00
Das ist schwer zu erklären, aber warum nicht?)

**Comment by Christoph142** [comment] 2015-02-02 08:01
Gute Frage. Danke auf jeden Fall ;)
Sonst passt alles?
Dann packe ich die Erweiterung jetzt und lade sie in den Store :+1:

**Comment by bratukham** [comment] 2015-02-02 08:07
Ja, ich denke so.

Wie heißt die Erweiterung in Store?

**Comment by Christoph142** [comment] 2015-02-02 08:28
Gut :)
https://addons.opera.com/extensions/details/modern-scroll ;)

**Comment by bratukham** [comment] 2015-02-02 08:31
Danke, aber ich meinte Google Webstore.:) Möchte die Erweiterung auch dort sehen.

**Comment by Christoph142** [comment] 2015-02-02 08:34
Warte mal ein paar Tage. Extension.Zone veröffentlicht einen Artikel von mir, warum meine Erweiterungen niemal im Google Store zu finden sein werden. Ich verlink ihn dir dann hier...

**Comment by bratukham** [comment] 2015-02-02 08:49
Okay, just added the link somewhere in the repo. :)

It's seems like the problem is still not fixed.

**Comment by Christoph142** [comment] 2015-02-02 09:36
Yeah, you seem to be right about it. Strange. It did work a few minutes ago :confused:

**Comment by Christoph142** [comment] 2015-02-02 09:43
And now it's working again. Driving me insane....?!

**Comment by Christoph142** [comment] 2015-02-02 09:50
I can't reproduce it anymore. So I can't investigate or fix it... We'll have to see if this was a temporary glitch or if I need to publish an additional version 3.0.7...

**Comment by bratukham** [comment] 2015-02-02 09:53
For me it is always the same...

**Comment by Christoph142** [comment] 2015-02-02 09:55
and 3.0.5 is always fine?

**Comment by Christoph142** [comment] 2015-02-02 10:09
Which browser do you use for testing btw?

**Comment by bratukham** [comment] 2015-02-02 10:11
In ver. 3.0.5 the custom srcollbars are everywhere (works as expected), but sometimes the appearance of the scrollbars is really strange.

**Comment by bratukham** [comment] 2015-02-02 10:12
I use Google Chrome Version 40.0.2214.94 m
On Windows 7 x64

**Comment by Christoph142** [comment] 2015-02-02 10:38
OK, i packed the extension and uploaded it as Release Client. Please try 3.0.6 by installing the packed(!) version and tell me if the issue is still reproducible.

**Comment by Christoph142** [comment] 2015-02-02 11:01
upd: I just installed 3.0.5 and it's the same issue. It only happens if the site loads in background. Can you confirm this?

**Comment by Christoph142** [comment] 2015-02-02 11:11
and another update on this one: 3.0.6 seems to cause this when navigating to another page, too. That does not happen with older versions. Reloading the page fixes this. I'm almost 100% sure that this is some weird Chromium issue and not a bug in the extension itself...
Will require some more investigation, but I'm not gonna do that for 3.0.6.

**Comment by Christoph142** [comment] 2015-02-02 11:42
As I assumed: There's an issue in Chromium -.-
Testcase: http://jsfiddle.net/n7fn8bx5/
Chromium bug filed: https://code.google.com/p/chromium/issues/detail?id=454346

**Comment by bratukham** [comment] 2015-02-02 11:56
Just made a couple of tests.
On Win7 x64 the scrollbars are not replaced for both versions (3.0.5 and 3.0.6).
On Win8.1 x64 the scrollbars are replaced, but only for 3.0.5 and behavior is really strange in this case.

Your test http://jsfiddle.net/n7fn8bx5/ is not work for both OS versions.

Maybe you need to find other solution while this bug is not fixed by Chromium developers?

**Comment by bratukham** [comment] 2015-02-02 12:00
Just reloaded page on Win8.1 x64 and the custom scrollbars disappeared 0_o

Maybe it depends on the settings of the extensions?

I will play with it a little bit more and will give you some info if I figure out something.

**Comment by Christoph142** [comment] 2015-02-05 16:43
@bratukham
https://twitter.com/christoph142/status/563375426937319424

**Comment by Christoph142** [comment] 2016-06-24 08:52
The Chromium bug seems to have been fixed. Do you still see this issue or can we close it? :)

**Comment by NguyenASang** [comment] 2021-09-11 13:37
This is the longest issue I have ever seen before :o
Is there a way to fix it or we need to wait for several years XD

**Comment by Christoph142** [comment] 2021-09-11 13:57
The Chromium issue has been fixed in 2017.

**Closed by Christoph142** 2021-09-11 13:57 UTC
Labels: Chromium bug
